<?php

/**
 * Implementation of hook_menu().
 */
function tenderapp_sso_menu() {
  $items = array();

  $items['admin/settings/tenderapp_sso'] = array(
    'title' => t('Tender App SSO Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tenderapp_sso_settings'),
    'access arguments' => array('administer tenderapp_sso'),
    'type' => MENU_CALLBACK,
    'file' => 'tenderapp_sso.admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_perm().
 */
function tenderapp_sso_perm() {
  return array('administer tenderapp_sso');
}

/**
 * Implementation of hook_help().
 */
function tenderapp_sso_help($path, $arg) {
  switch ($path) {
    case 'admin/help#tenderapp_sso':
      return '<p>' . t('The Tender App SSO Module lets you easily generate a Multipass link in any one of your theme templates') . '</p>';
  }
}

/**
 * Implementation of hook_theme().
 */
function tenderapp_sso_theme() {
  return array(
    'multipass' => array(
      'arguments' => array('link' => NULL, 'sso_key' => NULL, 'key' => NULL, 'anchor_text' => "Support"),
    ),
  );
}

/**
 * Generates the Tender API Key
 *
 * @param string $link Your tender link http://yourapp.tender.com
 * @param string $sso_key Your Tender site Key
 * @param string $key Your Tender SSO API Key
 * @param string $text The visible text between the anchor element
 */
function theme_multipass($link = NULL, $sso_key = NULL, $key = NULL, $anchor_text = NULL) {
  global $user;

  // Allow users to pass in different values, but default to our stored settings.
  if ($link == NULL) {
    $link = variable_get('tenderapp_sso_link', NULL);
  }
  if ($sso_key == NULL) {
    $sso_key = variable_get('tenderapp_sso_sso_key', NULL);
  }
  if ($key == NULL) {
    $key = variable_get('tenderapp_sso_api_key', NULL);
  }
  if ($anchor_text == NULL) {
    $anchor_text = variable_get('tenderapp_sso_anchor_text', "Support");
  }

  // Checks to see if a tender link was even entered
  if ($link == NULL) {
    drupal_set_message( t("You haven't entered your Tender App URL"), "error");
    return;
  }

  if ($key == NULL) {
    drupal_set_message( t("You haven't entered your Tender Key"));
    return;
  }
  elseif ($sso_key == NULL) {
    drupal_set_message( t("You haven't entered your SSO API Key"));
    return;
  }
  // Checks to see if the user is logged in if not just returns the link
  if ($user->uid == 0) {
    return '<a href="http://' . $link . '">' . $anchor_text . '</a>';
  }

  //Is the user's email setup?
  if ($user->mail == "") {
    drupal_set_message( t("You must be logged in for support"), "error");
  }

  $tender_params = array(
    'unique_id' => $user->uid,
    'name'      => $user->name,
    'email'     => $user->mail,
    'sso_key'   => $sso_key,
    'site_key'  => $key,
    'expires'   => date("Y-m-d H:i:s", strtotime("+30 minutes")),
    'trusted'   => TRUE,
  );

  //Finally generate the Tender URL
  return '<a href="http://' . $link  . _getTenderLink($tender_params) . '">' . $anchor_text . '</a>';
}

/**
 * Generates a Tender API link, accepting parameters and doing all the
 * hashing, security-ing, and modify-ing.
 *
 * @param array $params
 * @return void
 */
function _getTenderLink($params) {
  $hash = hash('sha1', $params['sso_key'] . $params['site_key'], TRUE);

  //Remove the API & SSO Key from the Params
  unset($params['sso_key']);
  unset($params['site_key']);

  $saltedHash = drupal_substr($hash, 0, 16);

  $iv= "OpenSSL for Ruby";

  $data = json_encode($params);

  for ($i = 0; $i < 16; $i++) {
      $data[$i] = $data[$i] ^ $iv[$i];
  }

  $pad = 16 - (drupal_strlen($data) % 16);
  $data = $data . str_repeat(chr($pad), $pad);
  $cipher = mcrypt_module_open(MCRYPT_RIJNDAEL_128, '', 'cbc', '');
  mcrypt_generic_init($cipher, $saltedHash, $iv);
  $encryptedData = mcrypt_generic($cipher, $data);
  mcrypt_generic_deinit($cipher);

  $multipass = urlencode(base64_encode($encryptedData));

  return "?sso={$multipass}";
}